- debug:
    var: ansible_distribution_major_version
    verbosity: 1

- debug:
    var: ansible_distribution
    verbosity: 1

- name: Include distribution specific variables.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "default.yml"

- name: Install packages.
  ansible.builtin.package:
    name: "{{ python_os_packages }}"

- name: configure pip.
  ansible.builtin.template:
    src: "templates/etc/pip.conf.j2"
    dest: "/etc/pip.conf"
    mode: 0644
  when:
    - python_global_index_url is defined

- name: Update setuptools.
  ansible.builtin.pip:
    name: "{{ python_pip_package_setuptools }}"
    executable: pip3
  when: python_update_setuptools

- name: Update pip.
  ansible.builtin.pip:
    name: "{{ python_pip_package_pip }}"
    executable: pip3
  when: python_update_pip

- name: Install pip packages.
  ansible.builtin.pip:
    name: "{{ python_pip_packages }}"
    executable: pip3
