- name: Include distribution specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_lsb.major_release }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: Install packages.
  package:
    name: "{{ python_os_packages }}"

- name: configure pip.
  template:
    src: "templates/etc/pip.conf.j2"
    dest: "/etc/pip.conf"
    mode: 0644
  when:
    - python_global_index_url is defined

- name: Update setuptools.
  pip:
    name: "{{ python_pip_package_setuptools }}"
    executable: pip3

- name: Update pip.
  pip:
    name: "{{ python_pip_package_pip }}"
    executable: pip3

- name: Install pip packages.
  pip:
    name: "{{ python_pip_packages }}"
    executable: pip3
